/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.elicarlos.sevenDaysOsCode;


import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
/*import static java.util.stream.DoubleStream.builder;*/


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws URISyntaxException, IOException, InterruptedException {
        System.out.println(new App().getGreeting()); 
        
       String apiKey = "";
    
       // Criar um cliente http
       HttpClient client = HttpClient.newHttpClient();
       //Criando um requisicao
      
       //Criado um objeto de requisicao
       HttpRequest request = HttpRequest
               .newBuilder()
               .uri(new URI("https://imdb-api.com/API/Top250Movies/" + apiKey))
               .header("Content-Type", "application/json")
               .GET()
               .build();
       
       //Criando um objeto de requisicao
       HttpResponse<String> response = client.send(request,
                HttpResponse.BodyHandlers.ofString());
       
        System.out.println(response.body());
           
    }
}
        
    
    